#!/bin/bash

echo "🎨 Running SwiftFormat..."
if ! command -v swiftformat >/dev/null 2>&1; then
    echo "⚠️ SwiftFormat not installed. Install with 'brew install swiftformat' or execute './setup.sh.'"
    exit 1
fi
swiftformat . --quiet
if [ $? -ne 0 ]; then
    echo "❌ SwiftFormat failed."
    exit 1
fi

echo "🔍 Running SwiftLint..."
if ! command -v swiftlint >/dev/null 2>&1; then
    echo "⚠️ SwiftLint not installed. Install with 'brew install swiftlint' or execute './setup.sh.'"
    exit 1
fi
swiftlint --quiet
swiftlint lint --fix --strict
if [ $? -ne 0 ]; then
    echo "❌ SwiftLint failed."
    exit 1
fi

git add .

echo "✅ Pre-commit checks passed!"
