name: Ora
options:
  bundleIdPrefix: com.orabrowser

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.0

targets:
  ora:
    type: application
    platform: "macOS"
    deploymentTarget: "15.0"
    sources:
      - path: ora
        excludes:
          - "Icons/**"
    resources:
      - path: ora/Modules/EmojiPicker/emoji-set.json
      - path: ora/Resources
        optional: true
    dependencies:
      - package: Sparkle

    preBuildScripts:
      - name: "Copy Icon Bundle"
        inputFiles:
          - "$(SRCROOT)/ora/Icons/OraIcon.icon"
          - "$(SRCROOT)/ora/Icons/OraIconDev.icon"
        outputFiles:
          - "$(BUILT_PRODUCTS_DIR)/$(PRODUCT_NAME).app/Contents/Resources/OraIcon.icon"
          - "$(BUILT_PRODUCTS_DIR)/$(PRODUCT_NAME).app/Contents/Resources/OraIconDev.icon"
        script: |
          ICON_SRC_DEV="$SRCROOT/ora/Icons/OraIconDev.icon"
          ICON_SRC_RELEASE="$SRCROOT/ora/Icons/OraIcon.icon"
          ICON_DST="$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/Resources/"
          if [ "$CONFIGURATION" = "Debug" ]; then
              echo "Using OraIconDev.icon for Debug build"
              cp -R "$ICON_SRC_DEV" "$ICON_DST"
          else
              echo "Using OraIcon.icon for Release build"
              cp -R "$ICON_SRC_RELEASE" "$ICON_DST"
          fi

    info:
      path: ora/Info.plist
      properties:
        SUFeedURL: "https://the-ora.github.io/browser/appcast.xml"
        SUPublicEDKey: "Ozj+rezzbJAD76RfajtfQ7rFojJbpFSCl/0DcFSBCTI="
        SUEnableAutomaticChecks: YES
        
    entitlements:
      path: ora/ora.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.assets.movies.read-only: true
        com.apple.security.assets.music.read-only: true
        com.apple.security.assets.pictures.read-only: true
        com.apple.security.cs.allow-jit: true
        com.apple.security.device.audio-input: true
        com.apple.security.device.camera: true
        com.apple.security.files.downloads.read-write: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
        com.apple.security.print: true

    settings:
      base:
        SWIFT_VERSION: 5.9
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: 0.2.3
        CURRENT_PROJECT_VERSION: 91
        PRODUCT_NAME: Ora
        PRODUCT_BUNDLE_IDENTIFIER: com.orabrowser.app
        GENERATE_INFOPLIST_FILE: YES
        SUFeedURL: "https://the-ora.github.io/browser/appcast.xml"
        SUPublicEDKey: "Ozj+rezzbJAD76RfajtfQ7rFojJbpFSCl/0DcFSBCTI="
        SUEnableAutomaticChecks: YES
      configs:
        Debug:
          ASSETCATALOG_COMPILER_APPICON_NAME: OraIconDev
        Release:
          ASSETCATALOG_COMPILER_APPICON_NAME: OraIcon

schemes:
  ora:
    shared: true
    build:
      targets:
        ora: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
